/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as VideoIndexImport } from './routes/video/index'
import { Route as SutraIndexImport } from './routes/sutra/index'
import { Route as DhammaIndexImport } from './routes/dhamma/index'
import { Route as CalendarIndexImport } from './routes/calendar/index'
import { Route as BookIndexImport } from './routes/book/index'
import { Route as SutraCategoryImport } from './routes/sutra/$category'
import { Route as SutraDetailsIdImport } from './routes/sutra/details.$id'

// Create Virtual Routes

const FavoritesIndexLazyImport = createFileRoute('/favorites/')()
const SutraSearchLazyImport = createFileRoute('/sutra/search')()
const FavoritesDetailsIdLazyImport = createFileRoute('/favorites/details/$id')()

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesIndexLazyRoute = FavoritesIndexLazyImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/favorites/index.lazy').then((d) => d.Route),
)

const VideoIndexRoute = VideoIndexImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => rootRoute,
} as any)

const SutraIndexRoute = SutraIndexImport.update({
  id: '/sutra/',
  path: '/sutra/',
  getParentRoute: () => rootRoute,
} as any)

const DhammaIndexRoute = DhammaIndexImport.update({
  id: '/dhamma/',
  path: '/dhamma/',
  getParentRoute: () => rootRoute,
} as any)

const CalendarIndexRoute = CalendarIndexImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRoute,
} as any)

const BookIndexRoute = BookIndexImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRoute,
} as any)

const SutraSearchLazyRoute = SutraSearchLazyImport.update({
  id: '/sutra/search',
  path: '/sutra/search',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sutra/search.lazy').then((d) => d.Route))

const SutraCategoryRoute = SutraCategoryImport.update({
  id: '/sutra/$category',
  path: '/sutra/$category',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesDetailsIdLazyRoute = FavoritesDetailsIdLazyImport.update({
  id: '/favorites/details/$id',
  path: '/favorites/details/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/favorites/details.$id.lazy').then((d) => d.Route),
)

const SutraDetailsIdRoute = SutraDetailsIdImport.update({
  id: '/sutra/details/$id',
  path: '/sutra/details/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/sutra/$category': {
      id: '/sutra/$category'
      path: '/sutra/$category'
      fullPath: '/sutra/$category'
      preLoaderRoute: typeof SutraCategoryImport
      parentRoute: typeof rootRoute
    }
    '/sutra/search': {
      id: '/sutra/search'
      path: '/sutra/search'
      fullPath: '/sutra/search'
      preLoaderRoute: typeof SutraSearchLazyImport
      parentRoute: typeof rootRoute
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookIndexImport
      parentRoute: typeof rootRoute
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarIndexImport
      parentRoute: typeof rootRoute
    }
    '/dhamma/': {
      id: '/dhamma/'
      path: '/dhamma'
      fullPath: '/dhamma'
      preLoaderRoute: typeof DhammaIndexImport
      parentRoute: typeof rootRoute
    }
    '/sutra/': {
      id: '/sutra/'
      path: '/sutra'
      fullPath: '/sutra'
      preLoaderRoute: typeof SutraIndexImport
      parentRoute: typeof rootRoute
    }
    '/video/': {
      id: '/video/'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoIndexImport
      parentRoute: typeof rootRoute
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sutra/details/$id': {
      id: '/sutra/details/$id'
      path: '/sutra/details/$id'
      fullPath: '/sutra/details/$id'
      preLoaderRoute: typeof SutraDetailsIdImport
      parentRoute: typeof rootRoute
    }
    '/favorites/details/$id': {
      id: '/favorites/details/$id'
      path: '/favorites/details/$id'
      fullPath: '/favorites/details/$id'
      preLoaderRoute: typeof FavoritesDetailsIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sutra/$category': typeof SutraCategoryRoute
  '/sutra/search': typeof SutraSearchLazyRoute
  '/book': typeof BookIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/dhamma': typeof DhammaIndexRoute
  '/sutra': typeof SutraIndexRoute
  '/video': typeof VideoIndexRoute
  '/favorites': typeof FavoritesIndexLazyRoute
  '/sutra/details/$id': typeof SutraDetailsIdRoute
  '/favorites/details/$id': typeof FavoritesDetailsIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sutra/$category': typeof SutraCategoryRoute
  '/sutra/search': typeof SutraSearchLazyRoute
  '/book': typeof BookIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/dhamma': typeof DhammaIndexRoute
  '/sutra': typeof SutraIndexRoute
  '/video': typeof VideoIndexRoute
  '/favorites': typeof FavoritesIndexLazyRoute
  '/sutra/details/$id': typeof SutraDetailsIdRoute
  '/favorites/details/$id': typeof FavoritesDetailsIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sutra/$category': typeof SutraCategoryRoute
  '/sutra/search': typeof SutraSearchLazyRoute
  '/book/': typeof BookIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/dhamma/': typeof DhammaIndexRoute
  '/sutra/': typeof SutraIndexRoute
  '/video/': typeof VideoIndexRoute
  '/favorites/': typeof FavoritesIndexLazyRoute
  '/sutra/details/$id': typeof SutraDetailsIdRoute
  '/favorites/details/$id': typeof FavoritesDetailsIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sutra/$category'
    | '/sutra/search'
    | '/book'
    | '/calendar'
    | '/dhamma'
    | '/sutra'
    | '/video'
    | '/favorites'
    | '/sutra/details/$id'
    | '/favorites/details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sutra/$category'
    | '/sutra/search'
    | '/book'
    | '/calendar'
    | '/dhamma'
    | '/sutra'
    | '/video'
    | '/favorites'
    | '/sutra/details/$id'
    | '/favorites/details/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sutra/$category'
    | '/sutra/search'
    | '/book/'
    | '/calendar/'
    | '/dhamma/'
    | '/sutra/'
    | '/video/'
    | '/favorites/'
    | '/sutra/details/$id'
    | '/favorites/details/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SutraCategoryRoute: typeof SutraCategoryRoute
  SutraSearchLazyRoute: typeof SutraSearchLazyRoute
  BookIndexRoute: typeof BookIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  DhammaIndexRoute: typeof DhammaIndexRoute
  SutraIndexRoute: typeof SutraIndexRoute
  VideoIndexRoute: typeof VideoIndexRoute
  FavoritesIndexLazyRoute: typeof FavoritesIndexLazyRoute
  SutraDetailsIdRoute: typeof SutraDetailsIdRoute
  FavoritesDetailsIdLazyRoute: typeof FavoritesDetailsIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SutraCategoryRoute: SutraCategoryRoute,
  SutraSearchLazyRoute: SutraSearchLazyRoute,
  BookIndexRoute: BookIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  DhammaIndexRoute: DhammaIndexRoute,
  SutraIndexRoute: SutraIndexRoute,
  VideoIndexRoute: VideoIndexRoute,
  FavoritesIndexLazyRoute: FavoritesIndexLazyRoute,
  SutraDetailsIdRoute: SutraDetailsIdRoute,
  FavoritesDetailsIdLazyRoute: FavoritesDetailsIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/sutra/$category",
        "/sutra/search",
        "/book/",
        "/calendar/",
        "/dhamma/",
        "/sutra/",
        "/video/",
        "/favorites/",
        "/sutra/details/$id",
        "/favorites/details/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/sutra/$category": {
      "filePath": "sutra/$category.tsx"
    },
    "/sutra/search": {
      "filePath": "sutra/search.lazy.tsx"
    },
    "/book/": {
      "filePath": "book/index.tsx"
    },
    "/calendar/": {
      "filePath": "calendar/index.tsx"
    },
    "/dhamma/": {
      "filePath": "dhamma/index.tsx"
    },
    "/sutra/": {
      "filePath": "sutra/index.tsx"
    },
    "/video/": {
      "filePath": "video/index.tsx"
    },
    "/favorites/": {
      "filePath": "favorites/index.lazy.tsx"
    },
    "/sutra/details/$id": {
      "filePath": "sutra/details.$id.tsx"
    },
    "/favorites/details/$id": {
      "filePath": "favorites/details.$id.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
