/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as VideoIndexImport } from './routes/video/index'
import { Route as SutraIndexImport } from './routes/sutra/index'
import { Route as DhammaIndexImport } from './routes/dhamma/index'
import { Route as CalendarIndexImport } from './routes/calendar/index'
import { Route as BookIndexImport } from './routes/book/index'
import { Route as SutraCategoryImport } from './routes/sutra/$category'
import { Route as SutraDetailsCategoryTitleImport } from './routes/sutra/details.$category.$title'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VideoIndexRoute = VideoIndexImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => rootRoute,
} as any)

const SutraIndexRoute = SutraIndexImport.update({
  id: '/sutra/',
  path: '/sutra/',
  getParentRoute: () => rootRoute,
} as any)

const DhammaIndexRoute = DhammaIndexImport.update({
  id: '/dhamma/',
  path: '/dhamma/',
  getParentRoute: () => rootRoute,
} as any)

const CalendarIndexRoute = CalendarIndexImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRoute,
} as any)

const BookIndexRoute = BookIndexImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRoute,
} as any)

const SutraCategoryRoute = SutraCategoryImport.update({
  id: '/sutra/$category',
  path: '/sutra/$category',
  getParentRoute: () => rootRoute,
} as any)

const SutraDetailsCategoryTitleRoute = SutraDetailsCategoryTitleImport.update({
  id: '/sutra/details/$category/$title',
  path: '/sutra/details/$category/$title',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/sutra/$category': {
      id: '/sutra/$category'
      path: '/sutra/$category'
      fullPath: '/sutra/$category'
      preLoaderRoute: typeof SutraCategoryImport
      parentRoute: typeof rootRoute
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookIndexImport
      parentRoute: typeof rootRoute
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarIndexImport
      parentRoute: typeof rootRoute
    }
    '/dhamma/': {
      id: '/dhamma/'
      path: '/dhamma'
      fullPath: '/dhamma'
      preLoaderRoute: typeof DhammaIndexImport
      parentRoute: typeof rootRoute
    }
    '/sutra/': {
      id: '/sutra/'
      path: '/sutra'
      fullPath: '/sutra'
      preLoaderRoute: typeof SutraIndexImport
      parentRoute: typeof rootRoute
    }
    '/video/': {
      id: '/video/'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoIndexImport
      parentRoute: typeof rootRoute
    }
    '/sutra/details/$category/$title': {
      id: '/sutra/details/$category/$title'
      path: '/sutra/details/$category/$title'
      fullPath: '/sutra/details/$category/$title'
      preLoaderRoute: typeof SutraDetailsCategoryTitleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sutra/$category': typeof SutraCategoryRoute
  '/book': typeof BookIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/dhamma': typeof DhammaIndexRoute
  '/sutra': typeof SutraIndexRoute
  '/video': typeof VideoIndexRoute
  '/sutra/details/$category/$title': typeof SutraDetailsCategoryTitleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sutra/$category': typeof SutraCategoryRoute
  '/book': typeof BookIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/dhamma': typeof DhammaIndexRoute
  '/sutra': typeof SutraIndexRoute
  '/video': typeof VideoIndexRoute
  '/sutra/details/$category/$title': typeof SutraDetailsCategoryTitleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sutra/$category': typeof SutraCategoryRoute
  '/book/': typeof BookIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/dhamma/': typeof DhammaIndexRoute
  '/sutra/': typeof SutraIndexRoute
  '/video/': typeof VideoIndexRoute
  '/sutra/details/$category/$title': typeof SutraDetailsCategoryTitleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sutra/$category'
    | '/book'
    | '/calendar'
    | '/dhamma'
    | '/sutra'
    | '/video'
    | '/sutra/details/$category/$title'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sutra/$category'
    | '/book'
    | '/calendar'
    | '/dhamma'
    | '/sutra'
    | '/video'
    | '/sutra/details/$category/$title'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sutra/$category'
    | '/book/'
    | '/calendar/'
    | '/dhamma/'
    | '/sutra/'
    | '/video/'
    | '/sutra/details/$category/$title'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SutraCategoryRoute: typeof SutraCategoryRoute
  BookIndexRoute: typeof BookIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  DhammaIndexRoute: typeof DhammaIndexRoute
  SutraIndexRoute: typeof SutraIndexRoute
  VideoIndexRoute: typeof VideoIndexRoute
  SutraDetailsCategoryTitleRoute: typeof SutraDetailsCategoryTitleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SutraCategoryRoute: SutraCategoryRoute,
  BookIndexRoute: BookIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  DhammaIndexRoute: DhammaIndexRoute,
  SutraIndexRoute: SutraIndexRoute,
  VideoIndexRoute: VideoIndexRoute,
  SutraDetailsCategoryTitleRoute: SutraDetailsCategoryTitleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/sutra/$category",
        "/book/",
        "/calendar/",
        "/dhamma/",
        "/sutra/",
        "/video/",
        "/sutra/details/$category/$title"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/sutra/$category": {
      "filePath": "sutra/$category.tsx"
    },
    "/book/": {
      "filePath": "book/index.tsx"
    },
    "/calendar/": {
      "filePath": "calendar/index.tsx"
    },
    "/dhamma/": {
      "filePath": "dhamma/index.tsx"
    },
    "/sutra/": {
      "filePath": "sutra/index.tsx"
    },
    "/video/": {
      "filePath": "video/index.tsx"
    },
    "/sutra/details/$category/$title": {
      "filePath": "sutra/details.$category.$title.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
